import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const measure = () => page.evaluate(async () => { let n = 0; const t0 = performance.now(); await new Promise((res) => { const f = () => { n++; if (performance.now() - t0 < 1500) requestAnimationFrame(f); else res(); }; requestAnimationFrame(f); }); return n / 1.5; });
await page.goto('about:blank');
console.log('blank', await measure());
await page.goto('http://localhost:5173/?unlock=all');
await page.waitForTimeout(2500);
console.log('game menu', await measure());
await page.evaluate(() => { document.querySelector('#game canvas').style.display = 'none'; });
console.log('canvas hidden', await measure());
await page.evaluate(() => { document.querySelector('#game canvas').style.display = ''; document.querySelector('.layer').style.display = 'none'; });
console.log('react layer hidden', await measure());
await page.evaluate(() => { const g = window.__TLM__.Director.game; g.scene.getScene('Overlay').sys.setVisible(false); });
console.log('overlay scene hidden', await measure());
await page.evaluate(() => { const g = window.__TLM__.Director.game; g.scene.getScene('Attract').sys.setVisible(false); });
console.log('attract hidden too', await measure());
await browser.close();
