import { chromium } from 'playwright';
const vp = process.env.VP ? process.env.VP.split('x').map(Number) : [1280, 720];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: vp[0], height: vp[1] } });
await page.goto('http://localhost:5173/?unlock=all');
await page.waitForTimeout(3000);
const fps = () => page.evaluate(async () => { const g = window.__TLM__.Director.game; const f0 = g.loop.frame; await new Promise((r) => setTimeout(r, 1500)); return (g.loop.frame - f0) / 1.5; });
console.log('base', await fps());
await page.evaluate(() => { const o = window.__TLM__.Director.game.scene.getScene('Overlay'); o.children.list.forEach(c => { if (c.type === 'TileSprite') c.setVisible(false); }); });
console.log('no tilesprites', await fps());
await page.evaluate(() => { const o = window.__TLM__.Director.game.scene.getScene('Overlay'); o.children.list.forEach(c => c.setVisible(false)); });
console.log('overlay all hidden', await fps());
await page.evaluate(() => { document.querySelector('.layer').innerHTML = ''; });
console.log('dom menu removed', await fps());
await page.evaluate(() => { const a = window.__TLM__.Director.game.scene.getScene('Attract'); a.children.list.forEach(c => c.setVisible(false)); });
console.log('attract hidden', await fps());
await browser.close();
