import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto(process.env.URL || 'http://localhost:5173/?unlock=all');
await page.waitForTimeout(3000);
const fps = () => page.evaluate(async () => { const g = window.__TLM__.Director.game; const f0 = g.loop.frame; await new Promise((r) => setTimeout(r, 1500)); return (g.loop.frame - f0) / 1.5; });
console.log('base', await fps());
await page.evaluate(() => window.__TLM__.Director.game.scene.stop('Attract'));
console.log('attract stopped', await fps());
await page.evaluate(() => window.__TLM__.Director.game.scene.stop('Overlay'));
console.log('overlay stopped', await fps());
await page.evaluate(() => window.__TLM__.Director.game.scene.stop('Boot'));
console.log('boot stopped', await fps());
const t = await page.evaluate(() => window.__TLM__.Director.game.textures.getTextureKeys().length);
console.log('textures', t);
await browser.close();
