import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto('http://localhost:5173/?unlock=all');
await page.waitForTimeout(3000);
const fps = () => page.evaluate(async () => { const g = window.__TLM__.Director.game; const f0 = g.loop.frame; await new Promise((r) => setTimeout(r, 1500)); return (g.loop.frame - f0) / 1.5; });
console.log('base', await fps());
await page.addStyleTag({ content: '.stage{box-shadow:none!important}' });
console.log('no box-shadow', await fps());
await page.addStyleTag({ content: '.app{background:#000!important}' });
console.log('no app gradient', await fps());
await page.addStyleTag({ content: '.stage{container-type:normal!important}' });
console.log('no container-type', await fps());
await page.addStyleTag({ content: '.layer{display:none!important}' });
console.log('no layers', await fps());
await page.addStyleTag({ content: '#game canvas{width:1280px!important;height:720px!important}' });
console.log('canvas fixed px', await fps());
const info = await page.evaluate(() => { const c = document.querySelector('#game canvas'); return { w: c.width, h: c.height, cw: c.clientWidth, style: c.getAttribute('style'), dpr: devicePixelRatio, ctxAttrs: window.__TLM__.Director.game.renderer.gl.getContextAttributes() }; });
console.log(JSON.stringify(info));
await browser.close();
